<a href="https://colab.research.google.com/github/MaanyaJohri/noteapp/blob/master/TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
a = tf.constant([[3,5],[7,3],[4,6]])
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 3],
       [4, 6]], dtype=int32)>

In [ ]:
b = tf.reduce_sum(a)
b

<tf.Tensor: shape=(), dtype=int32, numpy=28>

In [ ]:
c = tf.reduce_sum
c

<function tensorflow.python.ops.math_ops.reduce_sum(input_tensor, axis=None, keepdims=False, name=None)>

In [ ]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.2


In [ ]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:3]).numpy()
predictions

array([[ 0.26924974,  0.12814917,  0.12722991,  0.22740462,  0.37071612,
        -0.38637456, -0.07185873,  0.09411137,  0.03948136,  0.437843  ],
       [ 0.08121883,  0.02269781, -0.55171925,  0.11275658, -0.08622465,
         0.39844802, -0.7692553 ,  0.65395176, -0.61929286, -0.01985584],
       [ 0.2931096 , -0.01072136,  0.20637779,  0.0094782 ,  0.16932201,
         0.16691685,  0.19129188,  0.35953295, -0.36511034,  0.26432174]],
      dtype=float32)